#!/bin/bash
# run this script from the project root using `./scripts/build_docs.sh`

echo "-----------------------------------"
echo "Generating API reference via Sphinx"
echo "-----------------------------------"
cd docs || exit
make html
cd .. || exit


# run script to parse html generated by sphinx
echo "--------------------------------------------"
echo "Parsing Sphinx docs and moving to Docusaurus"
echo "--------------------------------------------"
mkdir -p "website/static/api/"

cwd=$(pwd)
SPHINX_HTML_DIR="website/static/api/"
cp -R "${cwd}/docs/build/html/" "${cwd}/${SPHINX_HTML_DIR}"
echo "Parsed Sucessfully"
echo "Moved location: ${SPHINX_HTML_DIR}"