name: Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2.2.2

      - name: Hash Python version
        id: hash
        run: echo ::set-output name=hash::$(python --version | sha256sum | cut -d' ' -f1)

      - name: Restore cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ steps.hash.outputs.hash }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3
