name: Security

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  # every Sunday at midnight
  schedule:
    - cron: '0 0 * * 0'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: python

      - name: Run CodeQL
        uses: github/codeql-action/analyze@v1

  ossar:
    name: OSSAR
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run OSSAR
        id: ossar
        uses: github/ossar-action@v1

      - name: Upload OSSAR results
        if: always()
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.ossar.outputs.sarifFile }}

  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/ci
            p/secrets
          auditOn: >-
            push
            pull_request
          generateSarif: true

      - name: Upload Semgrep results
        if: always()
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: semgrep.sarif
