name: Security

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # every Sunday at midnight
  schedule:
    - cron: '0 0 * * 0'

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Run OSSAR
        id: ossar
        uses: github/ossar-action@v1

      - name: Upload OSSAR results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.ossar.outputs.sarifFile }}
